// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyLCu3O4nAvsNzdT8zsJBirS9Yg60T5cA',
    appId: '1:34299614478:web:d095fdc731d0431b25335f',
    messagingSenderId: '34299614478',
    projectId: 'flutter-application-1-f17',
    authDomain: 'flutter-application-1-f17.firebaseapp.com',
    storageBucket: 'flutter-application-1-f17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1o6iP61A1ctv3XkMTmCfEzRF5tKq2iYk',
    appId: '1:34299614478:android:5bbb1dab68a6f01125335f',
    messagingSenderId: '34299614478',
    projectId: 'flutter-application-1-f17',
    storageBucket: 'flutter-application-1-f17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPmUayVX5r-dkeDFxy0YWhKONCAJpDVag',
    appId: '1:34299614478:ios:59eacaf9955d8d6d25335f',
    messagingSenderId: '34299614478',
    projectId: 'flutter-application-1-f17',
    storageBucket: 'flutter-application-1-f17.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPmUayVX5r-dkeDFxy0YWhKONCAJpDVag',
    appId: '1:34299614478:ios:0a4044dc41a5a32a25335f',
    messagingSenderId: '34299614478',
    projectId: 'flutter-application-1-f17',
    storageBucket: 'flutter-application-1-f17.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
